### PR TITLE
Updated Login/SignUp NAV

### PR DESCRIPTION
**Pull request by agonzalezengr**

### CODE REVIEW

**Review by yaritorres — APPROVED** [review]

**Review by APolk10 — COMMENTED** [review]
This looks good Az. I do have a question. Will we be able to redirect to a particular page based on a credentials variable from our database? I am hoping to redirect employees to one page, but employers to another on login.

**Review by selinaduran — COMMENTED** [review]
Great work with the authentication AZ!

**Comment by agonzalezengr** [comment]
> This looks good Az. I do have a question. Will we be able to redirect to a particular page based on a credentials variable from our database? I am hoping to redirect employees to one page, but employers to another on login.

Yes. We can assign rolls to each user and based on those rolls we can condition the code to direct users to their corresponding pages.

**Review by APolk10 — APPROVED** [review]
Thanks for getting back to me. Excited to implement this redirect feature.

**Pull request merged**
